auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20971520
  grpc_server_max_send_msg_size: 20971520

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  wal:
    dir: /loki/wal
  chunk_idle_period: 30m
  chunk_target_size: 1048576
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb:
    directory: /loki/index

  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 20
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: {{ inventory_loki_reject }}

chunk_store_config:
  max_look_back_period: {{ inventory_loki_retention }}
table_manager:
  retention_deletes_enabled: true
  retention_period: {{ inventory_loki_retention }}

ruler:
  external_url: https://monitoring.com/grafana/explore
#  external_labels:
#    project: {{ inventory_project_name }}
  alertmanager_url: http://{{ inventory_alertmanager_host }}:{{ inventory_alertmanager_port }}
  enable_api: true
  enable_alertmanager_v2: true