global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    type: {{ inventory_project_name }}
    node: {{ inventory_hostname }}

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #   - targets: ['localhost:9090']
  #     labels:
  #       node: {{ inventory_hostname }}
  #       service: prometheus

  - job_name: 'node_exporter_{{ inventory_project_name }}'
    static_configs:
    - targets: ['localhost:9100']
      labels:
        node: {{ inventory_hostname }}
        service: node-exporter
    relabel_configs:
      - source_labels: ['job']
        target_label: project
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
{% if inventory_host_prod is defined %}
        replacement: {{ inventory_host_prod }}:9100
{% else %}
        replacement: {{ ansible_host }}:9100
{% endif %}

  - job_name: 'fluent-bit_{{ inventory_project_name }}'
    metrics_path: '/api/v1/metrics/prometheus'
    static_configs:
    - targets: ['localhost:2020']
      labels:
        node: {{ inventory_hostname }}
        service: fluent-bit
    relabel_configs:
      - source_labels: ['job']
        target_label: project

  - job_name: 'cadvisor_{{ inventory_project_name }}'
    static_configs:
    - targets: ['localhost:8885']
      labels:
        node: {{ inventory_hostname }}
        service: cadvisor
    relabel_configs:
      - source_labels: ['job']
        target_label: project
{% if enable_open_stat_api | default("false") == "true" %}
  - job_name: '{{ complex_name }}'
    static_configs:
    - targets: ['{{ ansible_host }}:1397']
      labels:
        node: {{ inventory_hostname }}
        service: open_stat_api
{% endif %}