# Внимание!
# Этот сервис использует external volume сервиса prometheus.
# Сначала нужно развернуть сервис prometheus.

version: "3.7"

services:

  {{ inventory_thanos_sidecar_hostname }}:
    image: quay.io/thanos/thanos:{{ inventory_thanos_tag }}
    hostname: {{ inventory_thanos_sidecar_hostname }}
    container_name: {{ inventory_thanos_sidecar_hostname }}
#    network_mode: "host"
    volumes:
      - prometheus_prometheus_data:/prometheus
    ports:
      - 10915:10915
      - 10916:10916
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --grpc-address=0.0.0.0:10915
      - --http-address=0.0.0.0:10916
      - --prometheus.url=http://{{ inventory_prometheus_host }}:{{ inventory_prometheus_port }}
      - |
        --objstore.config=type: S3
        config:
          bucket: "transit-node-exporter-metrics"
          endpoint: "{{ inventory_minio_host }}:{ inventory_minio_port }"
          access_key: "admin"
          secret_key: "{{ inventory_minio_secret_key }}"
          insecure: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"  
    networks:
      - {{ inventory_monitoring_network }}           
    restart: always

networks:
  {{ inventory_monitoring_network }}:
    name: {{ inventory_monitoring_network }}

volumes:
  prometheus_prometheus_data:
    external: true
